// Code generated by go generate; DO NOT EDIT.
package wagogpu

import wago "github.com/wago-org/wago"

const (
	TypeI8               ElementType = 1
	TypeU8               ElementType = 2
	TypeI16              ElementType = 3
	TypeU16              ElementType = 4
	TypeI32              ElementType = 5
	TypeU32              ElementType = 6
	TypeF16              ElementType = 7
	TypeF32              ElementType = 8
	TypeI64              ElementType = 9
	TypeU64              ElementType = 10
	TypeF64              ElementType = 11
	V1OK                 int32       = 0
	V1CPUFallback        int32       = 1
	V1InvalidHandle      int32       = 2
	V1InvalidRange       int32       = 3
	V1TypeMismatch       int32       = 4
	V1InvalidBinding     int32       = 5
	V1LimitExceeded      int32       = 6
	V1DeviceError        int32       = 7
	V1ContentsLost       int32       = 8
	V1Cancelled          int32       = 9
	V1InvalidKernel      int32       = 10
	V1UnsupportedStorage int32       = 11
	V1InvalidState       int32       = 12
)

var elementSpecs = [...]elementSpec{
	{},
	{"I8", 1, wago.ValI32},
	{"U8", 1, wago.ValI32},
	{"I16", 2, wago.ValI32},
	{"U16", 2, wago.ValI32},
	{"I32", 4, wago.ValI32},
	{"U32", 4, wago.ValI32},
	{"F16", 2, wago.ValF32},
	{"F32", 4, wago.ValF32},
	{"I64", 8, wago.ValI64},
	{"U64", 8, wago.ValI64},
	{"F64", 8, wago.ValF64},
}
var bufferImports = [...]bufferImport{
	{name: "createBuffer", params: []wago.ValType{wago.ValI32, wago.ValI32}, results: []wago.ValType{wago.ValI32, wago.ValI32}},
	{name: "createBufferPacked", params: []wago.ValType{wago.ValI32, wago.ValI32}, results: []wago.ValType{wago.ValI64}},
	{name: "freeBuffer", params: []wago.ValType{wago.ValI32}, results: []wago.ValType{wago.ValI32}},
	{name: "bindBuffer", params: []wago.ValType{wago.ValI32, wago.ValI32}, results: []wago.ValType{wago.ValI32}},
	{name: "getBuffer", params: []wago.ValType{wago.ValI32}, results: []wago.ValType{wago.ValI32}},
	{name: "dispatch", params: []wago.ValType{wago.ValI32, wago.ValI32}, results: []wago.ValType{wago.ValI32}},
	{name: "setBuffer32", params: []wago.ValType{wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32}, results: []wago.ValType{wago.ValI32}},
	{name: "setBuffer64", params: []wago.ValType{wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI64, wago.ValI32}, results: []wago.ValType{wago.ValI32}},
	{name: "setBufferGC", params: []wago.ValType{wago.ValI32, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValI32}, results: []wago.ValType{wago.ValI32}},
	{name: "copyBuffer32", params: []wago.ValType{wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32}, results: []wago.ValType{wago.ValI32}},
	{name: "copyBuffer64", params: []wago.ValType{wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI64, wago.ValI32}, results: []wago.ValType{wago.ValI32}},
	{name: "copyBufferGC", params: []wago.ValType{wago.ValI32, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValI32}, results: []wago.ValType{wago.ValI32}},
	{name: "readBufferI8", params: []wago.ValType{wago.ValI32, wago.ValI32}, results: []wago.ValType{wago.ValI32}},
	{name: "writeBufferI8", params: []wago.ValType{wago.ValI32, wago.ValI32, wago.ValI32}, results: []wago.ValType{}},
	{name: "readBufferU8", params: []wago.ValType{wago.ValI32, wago.ValI32}, results: []wago.ValType{wago.ValI32}},
	{name: "writeBufferU8", params: []wago.ValType{wago.ValI32, wago.ValI32, wago.ValI32}, results: []wago.ValType{}},
	{name: "readBufferI16", params: []wago.ValType{wago.ValI32, wago.ValI32}, results: []wago.ValType{wago.ValI32}},
	{name: "writeBufferI16", params: []wago.ValType{wago.ValI32, wago.ValI32, wago.ValI32}, results: []wago.ValType{}},
	{name: "readBufferU16", params: []wago.ValType{wago.ValI32, wago.ValI32}, results: []wago.ValType{wago.ValI32}},
	{name: "writeBufferU16", params: []wago.ValType{wago.ValI32, wago.ValI32, wago.ValI32}, results: []wago.ValType{}},
	{name: "readBufferI32", params: []wago.ValType{wago.ValI32, wago.ValI32}, results: []wago.ValType{wago.ValI32}},
	{name: "writeBufferI32", params: []wago.ValType{wago.ValI32, wago.ValI32, wago.ValI32}, results: []wago.ValType{}},
	{name: "readBufferU32", params: []wago.ValType{wago.ValI32, wago.ValI32}, results: []wago.ValType{wago.ValI32}},
	{name: "writeBufferU32", params: []wago.ValType{wago.ValI32, wago.ValI32, wago.ValI32}, results: []wago.ValType{}},
	{name: "readBufferF16", params: []wago.ValType{wago.ValI32, wago.ValI32}, results: []wago.ValType{wago.ValF32}},
	{name: "writeBufferF16", params: []wago.ValType{wago.ValI32, wago.ValI32, wago.ValF32}, results: []wago.ValType{}},
	{name: "readBufferF32", params: []wago.ValType{wago.ValI32, wago.ValI32}, results: []wago.ValType{wago.ValF32}},
	{name: "writeBufferF32", params: []wago.ValType{wago.ValI32, wago.ValI32, wago.ValF32}, results: []wago.ValType{}},
	{name: "readBufferI64", params: []wago.ValType{wago.ValI32, wago.ValI32}, results: []wago.ValType{wago.ValI64}},
	{name: "writeBufferI64", params: []wago.ValType{wago.ValI32, wago.ValI32, wago.ValI64}, results: []wago.ValType{}},
	{name: "readBufferU64", params: []wago.ValType{wago.ValI32, wago.ValI32}, results: []wago.ValType{wago.ValI64}},
	{name: "writeBufferU64", params: []wago.ValType{wago.ValI32, wago.ValI32, wago.ValI64}, results: []wago.ValType{}},
	{name: "readBufferF64", params: []wago.ValType{wago.ValI32, wago.ValI32}, results: []wago.ValType{wago.ValF64}},
	{name: "writeBufferF64", params: []wago.ValType{wago.ValI32, wago.ValI32, wago.ValF64}, results: []wago.ValType{}},
}
