(module
 (import "wago_gpu_v1" "createBufferPacked" (func $create (param i32 i32) (result i64)))
 (import "wago_gpu_v1" "freeBuffer" (func $free (param i32) (result i32)))
 (import "wago_gpu_v1" "bindBuffer" (func $bind (param i32 i32) (result i32)))
 (import "wago_gpu_v1" "getBuffer" (func $get (param i32) (result i32)))
 (import "wago_gpu_v1" "readBufferF16" (func $read (param i32 i32) (result f32)))
 (import "wago_gpu_v1" "writeBufferF16" (func $write (param i32 i32 f32)))
 (import "wago_gpu_v1" "setBuffer32" (func $set (param i32 i32 i32 i32 i32) (result i32)))
 (import "wago_gpu_v1" "dispatch" (func $dispatch (param i32 i32) (result i32)))
 (memory 1)
 (global $status (mut i32) (i32.const 0))
 (func $check (param i32) (if (local.get 0) (then unreachable)))
 (func $kernel (export "wago_gpu.kernel.storage") (param $i i32)
  (call $write (call $get (i32.const 0)) (local.get $i)
   (f32.add (call $read (call $get (i32.const 0)) (local.get $i)) (f32.const 1))))
 (func $cpu (export "wago_gpu.cpu.storage") (param $n i32) (local $i i32)
  (block $done (loop $next
   (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
   (call $kernel (local.get $i))
   (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $next))))
 (func (export "status") (result i32) (global.get $status))
 (func (export "run") (result f32) (local $packed i64) (local $h i32) (local $result f32)
  (local.set $packed (call $create (i32.const 7) (i32.const 1)))
  (call $check (i32.wrap_i64 (i64.shr_u (local.get $packed) (i64.const 32))))
  (local.set $h (i32.wrap_i64 (local.get $packed)))
  (call $check (call $bind (i32.const 0) (local.get $h)))
  (i32.store16 (i32.const 0) (i32.const 0x3c00)) ;; binary16 value 1
  (call $check (call $set (local.get $h) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 1)))
  (global.set $status (call $dispatch (i32.const 1) (i32.const 1)))
  (if (i32.eq (global.get $status) (i32.const 1))
   (then (call $cpu (i32.const 1)))
   (else (call $check (global.get $status))))
  (local.set $result (call $read (local.get $h) (i32.const 0)))
  (call $check (call $free (local.get $h)))
  (local.get $result)))
