(module
(type $array (array (mut f32)))
(import "wago_gpu_v1" "setBufferGC" (func $set (param i32 i32 anyref i32 i32) (result i32)))
(import "wago_gpu_v1" "copyBufferGC" (func $copy (param i32 i32 anyref i32 i32) (result i32)))
(import "wago_gpu_v1" "createBufferPacked" (func $create (param i32 i32) (result i64)))
(import "wago_gpu_v1" "freeBuffer" (func $free (param i32) (result i32)))

(func $check (param i32) (if (local.get 0) (then unreachable)))
(func (export "wago_gpu.kernel.storage") (param i32))
(func (export "wago_gpu.cpu.storage") (param i32))
(func (export "run") (result f32) (local $packed i64) (local $h i32) (local $result f32) (local $a (ref null $array))
 (local.set $packed (call $create (i32.const 8) (i32.const 1)))
 (call $check (i32.wrap_i64 (i64.shr_u (local.get $packed) (i64.const 32))))
 (local.set $h (i32.wrap_i64 (local.get $packed)))
 (local.set $a (array.new_fixed $array 1 (f32.const 7)))
(call $check (call $set (local.get $h) (i32.const 0) (local.get $a) (i32.const 0) (i32.const 1)))
(array.set $array (local.get $a) (i32.const 0) (f32.const 0))
(call $check (call $copy (local.get $h) (i32.const 0) (local.get $a) (i32.const 0) (i32.const 1)))
(local.set $result (array.get $array (local.get $a) (i32.const 0)))
 (call $check (call $free (local.get $h)))
 (local.get $result)))
