// Command genabi derives Go declarations from the reviewed ABI table.
package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"strings"
)

func main() {
	var raw struct {
		Elements []struct {
			ID     int    `json:"id"`
			Suffix string `json:"suffix"`
			Name   string `json:"go_constant"`
			Bytes  int    `json:"stored_bytes"`
			Scalar string `json:"wasm_scalar"`
		} `json:"element_types"`
		Statuses []struct {
			Value int    `json:"value"`
			Name  string `json:"go_constant"`
		} `json:"statuses"`
		Imports []struct {
			Name            string `json:"name"`
			Params, Results []string
		} `json:"imports"`
	}
	b, err := os.ReadFile("spec/abi_v1.json")
	check(err)
	check(json.Unmarshal(b, &raw))
	var out strings.Builder
	out.WriteString("// Code generated by go generate; DO NOT EDIT.\npackage wagogpu\nimport wago \"github.com/wago-org/wago\"\nconst (\n")
	for _, e := range raw.Elements {
		fmt.Fprintf(&out, "%s ElementType = %d\n", e.Name, e.ID)
	}
	for _, s := range raw.Statuses {
		fmt.Fprintf(&out, "%s int32 = %d\n", s.Name, s.Value)
	}
	out.WriteString(")\nvar elementSpecs = [...]elementSpec{\n{},\n")
	for _, e := range raw.Elements {
		fmt.Fprintf(&out, "{\"%s\", %d, %s},\n", e.Suffix, e.Bytes, val(e.Scalar))
	}
	out.WriteString("}\nvar bufferImports = [...]bufferImport{\n")
	for _, i := range raw.Imports {
		fmt.Fprintf(&out, "{name:%q, params:[]wago.ValType{%s},results:[]wago.ValType{%s}},\n", i.Name, values(i.Params), values(i.Results))
	}
	out.WriteString("}\n")
	b, err = format.Source([]byte(out.String()))
	check(err)
	check(os.WriteFile("abi_generated.go", b, 0644))
}
func check(e error) {
	if e != nil {
		panic(e)
	}
}
func val(s string) string {
	return map[string]string{"i32": "wago.ValI32", "i64": "wago.ValI64", "f32": "wago.ValF32", "f64": "wago.ValF64", "anyref": "wago.ValAnyRef"}[s]
}
func values(v []string) string {
	r := make([]string, len(v))
	for i, s := range v {
		r[i] = val(s)
	}
	return strings.Join(r, ",")
}
